"""empty message

Revision ID: 0e8e249ca268
Revises: 7fd928331509
Create Date: 2017-07-17 17:38:32.073227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8e249ca268'
down_revision = '7fd928331509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_companies_company_name', 'companies', ['company_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_companies_company_name', 'companies', type_='unique')
    # ### end Alembic commands ###
