"""empty message

Revision ID: 0f36539ad38e
Revises: 0e8e249ca268
Create Date: 2017-07-29 18:09:13.245276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f36539ad38e'
down_revision = '0e8e249ca268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('announce_date', sa.Date(), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('cstat_adv_exp', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('cstat_rd_exp', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('cstat_rev', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('offer_status', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'offer_status')
    op.drop_column('companies', 'cstat_rev')
    op.drop_column('companies', 'cstat_rd_exp')
    op.drop_column('companies', 'cstat_adv_exp')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'announce_date')
    # ### end Alembic commands ###
