"""empty message

Revision ID: 7fd928331509
Revises: 
Create Date: 2017-07-13 22:57:25.069699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd928331509'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_url', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('num_reviews', sa.Integer(), nullable=True),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('offer_size', sa.Float(), nullable=True),
    sa.Column('offer_type', sa.String(), nullable=True),
    sa.Column('offer_price', sa.Float(), nullable=True),
    sa.Column('pct_change_fd', sa.Float(), nullable=True),
    sa.Column('pct_change_3m', sa.Float(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('num_employees', sa.Integer(), nullable=True),
    sa.Column('ind_sector', sa.String(), nullable=True),
    sa.Column('ind_group', sa.String(), nullable=True),
    sa.Column('sic_code', sa.Integer(), nullable=True),
    sa.Column('sic_name', sa.String(), nullable=True),
    sa.Column('use_of_proceeds', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('unique_company_reviews_company_id_review_id', 'company_reviews', ['company_id', 'review_id'])
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_date', sa.Date(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('current_employee', sa.Boolean(), nullable=True),
    sa.Column('years_employed', sa.Float(), nullable=True),
    sa.Column('review_summary', sa.String(), nullable=True),
    sa.Column('pros', sa.String(), nullable=True),
    sa.Column('cons', sa.String(), nullable=True),
    sa.Column('advice_to_mgmt', sa.String(), nullable=True),
    sa.Column('outlook', sa.Integer(), nullable=True),
    sa.Column('recommends', sa.Integer(), nullable=True),
    sa.Column('approves_of_ceo', sa.Integer(), nullable=True),
    sa.Column('overall', sa.Integer(), nullable=True),
    sa.Column('career_opportunities', sa.Integer(), nullable=True),
    sa.Column('comp_benefits', sa.Integer(), nullable=True),
    sa.Column('culture_values', sa.Integer(), nullable=True),
    sa.Column('senior_management', sa.Integer(), nullable=True),
    sa.Column('work_life_balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_company_reviews_company_id_review_id','company_reviews')
    op.drop_table('reviews')
    op.drop_table('company_reviews')
    op.drop_table('companies')
    # ### end Alembic commands ###
